
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class AdminCourse extends javax.swing.JFrame {

    /**
     * Creates new form AdminCourse
     */
  public AdminCourse() throws SQLException {
        Connect();
        initComponents();
        AdminCourse_Load();
    }
    Connection con;
    PreparedStatement pst;
   ResultSet rs;
    DefaultTableModel d;
    
    
    public void Connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/applied","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminCourse.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void AdminCourse_Load(){
        int c;
        try {
            pst=con.prepareStatement("select * from courses");
            rs=pst.executeQuery();
             
            ResultSetMetaData rsd= rs.getMetaData();
            c=rsd.getColumnCount();
            d=(DefaultTableModel)jTable1.getModel();
            d.setRowCount(0);
            
            while(rs.next())
            {
                Vector v2=new Vector();
                
                for(int i=1;i<=c;i++)
                {
                    
                    v2.add(rs.getString("programme"));
                    v2.add(rs.getString("code"));
                    v2.add(rs.getString("course1"));
                    v2.add(rs.getString("course2"));
                    v2.add(rs.getString("course3")); 
                    v2.add(rs.getString("course4"));
                    v2.add(rs.getString("course5"));
                } 
                
                d.addRow(v2);
                
            }
                   
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcode = new javax.swing.JTextField();
        txtcs3 = new javax.swing.JComboBox<>();
        txtcs4 = new javax.swing.JComboBox<>();
        txtcs2 = new javax.swing.JComboBox<>();
        txtcs5 = new javax.swing.JComboBox<>();
        txtcs1 = new javax.swing.JComboBox<>();
        txtpro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Programme");

        jLabel3.setText("Code");

        jLabel4.setText("Course 1");

        jLabel5.setText("Course 2");

        jLabel6.setText("Course 3");

        jLabel7.setText("Course 4");

        jLabel8.setText("Course 5");

        txtcode.setBackground(new java.awt.Color(51, 255, 51));

        txtcs3.setBackground(new java.awt.Color(51, 255, 51));
        txtcs3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "maths", "physics", " " }));

        txtcs4.setBackground(new java.awt.Color(51, 255, 51));
        txtcs4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "data structures", "e-business", "social implications" }));

        txtcs2.setBackground(new java.awt.Color(51, 255, 51));
        txtcs2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "user interface", "web design" }));
        txtcs2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcs2ActionPerformed(evt);
            }
        });

        txtcs5.setBackground(new java.awt.Color(51, 255, 51));
        txtcs5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "kiswahili", "e-business" }));
        txtcs5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcs5ActionPerformed(evt);
            }
        });

        txtcs1.setBackground(new java.awt.Color(51, 255, 51));
        txtcs1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "e-business", "java 1", "java 2", " " }));
        txtcs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcs1ActionPerformed(evt);
            }
        });

        txtpro.setBackground(new java.awt.Color(102, 255, 102));
        txtpro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcs2, 0, 278, Short.MAX_VALUE)
                            .addComponent(txtpro)
                            .addComponent(txtcs1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcode)
                            .addComponent(txtcs3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtcs5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtcs4, 0, 278, Short.MAX_VALUE))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtpro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcs1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtcs2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtcs3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcs4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcs5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(24, 24, 24))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setText("COURSES");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "programme", "code", "course 1", "course 2", "course 3", "course 4", "course 5"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("REMOVE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton1)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2)
                        .addGap(47, 47, 47)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(jLabel1)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton3)
                                .addComponent(jButton4))))
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproActionPerformed

    private void txtcs5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcs5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcs5ActionPerformed

    private void txtcs2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcs2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcs2ActionPerformed

    private void txtcs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcs1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcs1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         try {
             d=(DefaultTableModel)jTable1.getModel();
     int  selectIndex=jTable1.getSelectedRow();
     
      txtpro.setText(d.getValueAt(selectIndex, 0).toString());
            
            String programme=txtpro.getText();
            String code=txtcode.getText();
           String course1=txtcs1.getSelectedItem().toString();
            String course2=txtcs2.getSelectedItem().toString();
            String course3=txtcs3.getSelectedItem().toString();
            String course4=txtcs4.getSelectedItem().toString();
            String course5 =txtcs5.getSelectedItem().toString();
          
            pst=con.prepareStatement("update courses set code=?,course1=?, course2=?,course3=?,course4=?,course5=? where programme=?");
            
            //pst.setString(1, name);
            pst.setString(1, code);
            pst.setString(2, course1);
            pst.setString(3, course2);
            pst.setString(4,course3);
            pst.setString(5,course4);
            pst.setString(6,course5);
            pst.setString(7, programme);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(this, "Course Edited Successfully");
            jButton1.setEnabled(true);
             txtpro.setText("");
             txtcode.setText("");
            txtcs1.setSelectedIndex(-1);
             txtcs2.setSelectedIndex(-1);
             txtcs3.setSelectedIndex(-1);
             txtcs4.setSelectedIndex(-1);
             txtcs5.setSelectedIndex(-1);
             txtpro.requestFocus();
              AdminCourse_Load();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
                                           
        
        
        
                                        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         try {
             d=(DefaultTableModel)jTable1.getModel();
     int  selectIndex=jTable1.getSelectedRow();
     
          String programme=d.getValueAt(selectIndex, 0).toString();
            pst=con.prepareStatement("delete from courses where programme=?");
            pst.setString(1, programme);
             pst.executeUpdate();
             JOptionPane.showMessageDialog(this, "Course Removed Successfully");
            jButton1.setEnabled(true);
             txtpro.setText("");
             txtcode.setText("");
             txtcs1.setSelectedIndex(-1);
             txtcs2.setSelectedIndex(-1);
             txtcs3.setSelectedIndex(-1);
             txtcs4.setSelectedIndex(-1);
             txtcs5.setSelectedIndex(-1);
             txtpro.requestFocus();
              AdminCourse_Load();
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
                                   

     
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AdminAssign as=new AdminAssign();
        as.setVisible(true);
        setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           try {
            String programme=txtpro.getText();
            String code=txtcode.getText();
            String course1=txtcs1.getSelectedItem().toString();
            String course2=txtcs2.getSelectedItem().toString();
            String course3=txtcs3.getSelectedItem().toString();
            String course4=txtcs4.getSelectedItem().toString();
            String course5=txtcs5.getSelectedItem().toString();
          
           pst=con.prepareStatement("insert into courses(programme,code,course1,course2, course3,course4,course5)values(?,?,?,?,?,?,?)");
            
            pst.setString(1, programme);
            pst.setString(2, code);
            pst.setString(3, course1);
            pst.setString(4, course2);
            pst.setString(5, course3);
            pst.setString(6, course4);
            pst.setString(7, course5);
            pst.executeUpdate();
             JOptionPane.showMessageDialog(this, "Courses Assigned Successfully");
            
             txtpro.setText("");
             txtcode.setText("");
             txtcs1.setSelectedIndex(-1);
             txtcs2.setSelectedIndex(-1);
             txtcs3.setSelectedIndex(-1);
             txtcs4.setSelectedIndex(-1);
             txtcs5.setSelectedIndex(-1);
             txtpro.requestFocus();
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AdminCourse.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        d=(DefaultTableModel)jTable1.getModel();
     int  selectIndex=jTable1.getSelectedRow();
     
      txtpro.setText(d.getValueAt(selectIndex, 0).toString());
      txtcode.setText(d.getValueAt(selectIndex, 1).toString());
     txtcs1.setSelectedItem(d.getValueAt(selectIndex, 2).toString());
     txtcs2.setSelectedItem(d.getValueAt(selectIndex, 3).toString());
     txtcs3.setSelectedItem(d.getValueAt(selectIndex, 4).toString());
     txtcs4.setSelectedItem(d.getValueAt(selectIndex, 5).toString());
     txtcs5.setSelectedItem(d.getValueAt(selectIndex, 6).toString());
      
     jButton1.setEnabled(false);
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new AdminCourse().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(AdminCourse.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtcode;
    private javax.swing.JComboBox<String> txtcs1;
    private javax.swing.JComboBox<String> txtcs2;
    private javax.swing.JComboBox<String> txtcs3;
    private javax.swing.JComboBox<String> txtcs4;
    private javax.swing.JComboBox<String> txtcs5;
    private javax.swing.JTextField txtpro;
    // End of variables declaration//GEN-END:variables
}
